### PR TITLE
Add check for topic and data length. #17

### PR DESCRIPTION
**Pull request by AkosLukacs**
Hi!
Well, JSON serialization is not the most space efficient thing in the world :)

Added the check in the `publish` function.  If it's too long, throws an exception. The board stays connected to mqtt broker, and the next message (if it's not too long) is sent successfully. Free memory stays the same.

Added a note to the docs, and updated the minified file as well.

### CODE REVIEW

**Comment by olliephillips** [comment]
Great thank you for this (and providing the minified source also). I will merge. You'll also get a credit in the README. Thank you!!

**Comment by AkosLukacs** [comment]
\o/

Glad to help. Ping @gfwilliams Did you manually copy the code from this repository to the EspruinoDocs repo, or is there some kind of automation?

**Comment by olliephillips** [comment]
Hi @AkosLukacs It was manually copied, there's no automation at this time - I asked @gfwilliams. The code here is a few commits behind that offered on the Espruino site now.  While I do plan to update the Espruino repo regularly myself, it's likely to be frequently out-of-sync.  If you want your feature in there quickly, best advice would be to provide docs and code update yourself via PR.

**Comment by gfwilliams** [comment]
As @olliephillips says, it's manually copied, and the docs themselves are a bit different so aren't a straight copy. PRs for updates would be really good.

> The code here is a few commits behind that offered on the Espruino site

Do you mean behind, or ahead?

Just a thought about errors - if we're serious about keeping the size as small as possible maybe we should just `throw "ERR1"` and then document what that means? In something designed to be small it seems a shame to waste characters on errors that won't be used in code that's working correctly.

**Comment by olliephillips** [comment]
Ha. I meant "ahead" of course. It was late!
Re error message that's a good idea.  And maybe as emitted event? User can then choose how to handle? DIsconnect, log etc depending on code? Just a thought.

**Comment by AkosLukacs** [comment]
Hi, 
A shorter error message is a good idea, but I would prefix it with something, since (IIRC) there was no obvious clue about it's an error from the tinyMQTT library. `throw "tMQTT ERR1"`?

Also [at almost the same place in publish](https://github.com/olliephillips/tinyMQTT/blob/master/tinyMQTT.js#L98) there is that `if(_q.cn) { ...` that just silently fails if there is no active connection.
Another `throw`? Or forget about the exception, and just return an error code, since `socket.write` is synchronous anyways (i think), and that's less characters?
(oh, just noticed that the MQTT library does the same return if there is no connection)

Personally, I'm not sure about using events for "exceptional" events (in a sense that a network disconnect is expected, but too long data is probably not expected, it the code is working correctly). An event is probably easier to miss than an exception or a return code, you have to subscribe (more code), there is nothing to warn you about a typo. And you receive the event at a different place in the code, where won't have the same context. That may not matter, for example, right now I only publish a single message, but might not be obvious if you publish multiple messages...

**Comment by olliephillips** [comment]
Yes, I agree. I will pick this up, and I will update the Espruino docs when done. I wouldn't send @gfwilliams a pull request yet there is an open issue and publishing currently seems unreliable. I think I know what the problem is so will hopefully rectify

**Pull request merged**
