### PR TITLE
Change Subscription QoS to 0

### PR DESCRIPTION
**Pull request by atmosuwiryo**
Change Subscription QoS to 0
It is said only support QoS 0, but the subscription QoS is set to 1.

### CODE REVIEW

**Comment by atmosuwiryo** [comment]
The QoS=1 in the subscription can cause unknown first char like in this issue: https://github.com/olliephillips/tinyMQTT/issues/26

**Comment by olliephillips** [comment]
Thank you @atmosuwiryo QofS 1 on subscribe is a great catch. That it explains the behaviour seen by @cooltyn and reported in #26 is good news too. Apologies @cooltyn that I closed that issue, but if you can't replicate something, you have nowhere to start really :) I see this PR now includes the last will feature being debated in issue #27 an opened by @jejdacz, which rather makes that a fait accompli, but I think the feedback was leading to me asking for a PR on the feature in any event. I am going to merge this. Thank you again. You will all get a credit in the README when I next get chance.

**Comment by atmosuwiryo** [comment]
Oh, i'm just want to make PR about QoS.

For the (Last Will and Testament)LWT, I need it for my project. I've add comment about it in here https://github.com/olliephillips/tinyMQTT/issues/27#issuecomment-533469381

>You will all get a credit in the README when I next get chance.

Thank You.

**Comment by olliephillips** [comment]
> Oh, i'm just want to make PR about QoS.

Unfortunately that's a git thing.  When a PR is open we get all subsequent commits on the branch. There's no problem, that feature was going in anyway I think and all parties have been credited in the readme now. Thanks for your help.

**Pull request merged**
