### PR TITLE
fixed reconnect, fixed double disconnect event

### PR DESCRIPTION
**Pull request by The-Futur1st**

### CODE REVIEW

**Review by olliephillips — APPROVED** [review]
This looks good, the connection checks are an improvement. Thanks.

**Comment by The-Futur1st** [comment]
Additionally, you can add method to check connection status
```
TMQ.prototype.connected = function() {
	return _q.cn;
};
```

I use it in this way:
```
function setRelayState(state) {
  if(relay_state == state)
    return;
  Pin(D12).write(relay_state);
  if(mqtt && mqtt.connected())
    mqtt.publish('/relay/id0', relay_state.toString());
}
```

**Comment by olliephillips** [comment]
Hi yes. Maybe we can. One of the downsides of the package design is that ```_q``` is global, so you can interrogate ```_q.cn``` from code outside of the mqtt object. You provide a sensible abstraction here, but it'll only make the package less 'tiny' - so I'm not sure.

**Comment by The-Futur1st** [comment]
Yes, it is a good idea. Less code == less issues) Especially when we deal with esp8266)

**Pull request merged**
